service:
  name: testkit-api
#app: your-app-name
#tenant: your-tenant-name

plugins:
  - serverless-webpack
  - serverless-domain-manager

custom:
  stage: ${opt:stage, self:provider.stage}
  customDomain:
    domainName: api-${self:custom.stage}.testkit.link
    certificateName: 'testkit.link'
    basePath: 'users'
    stage: ${self:custom.stage}
    createRoute53Record: true

provider:
  name: aws
  region: eu-west-1
  endpointType: regional
  runtime: nodejs10.x
  profile: testkit-serverless-admin
  environment:
    stage: ${self:custom.stage}
  iamRoleStatements: ${file(../common/common.yml)}

resources:
  - ${file(../common/api-gateway-errors.yml)}

functions:
  auth:
    handler: api.auth
    cors:
      origin: '*'
  get-or-create-user:
    handler: api.getOrCreateUser
    events:
      - http:
          method: get
          path: 'current'
          cors:
            origin: '*'
          authorizer: auth
