Resources:
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: testkit-${self:custom.stage}-users
      AttributeDefinitions:
        - AttributeName: userid
          AttributeType: S
      KeySchema:
        - AttributeName: userid
          KeyType: HASH
      # Set the capacity to auto-scale
      BillingMode: PAY_PER_REQUEST
Outputs:
  UsersTableArn:
    Value:
      Fn::GetAtt:
        - UsersTable
        - Arn
    Export:
      Name: ${self:custom.stage}-UsersTableArn
